title: Remy Grangien # name of the site
author: Remy Grangien # name of site's author
email: remygrangien@protonmail.com # email of site's author
url: https://remygrangien.github.io # root address of the site
description: I am currently completing my undergraduate studies at the University of Wollongong. Here you can find what work I have been working on, particularily as it relates to artificial intelligence. 

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

#theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme: no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
